name: Release Asset

on:
  release:
    types: [published]

# Add explicit permissions for the workflow
permissions:
  contents: write

jobs:
  build:
    name: Create consistent ZIP file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create clean build directory
        run: |
          mkdir -p build/aco
          cp -r * build/aco/ 2>/dev/null || :
          rm -rf build/aco/.git build/aco/.github build/aco/.DS_Store build/aco/*/.DS_Store
          cd build && zip -r aco.zip aco
      
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/aco.zip 