name: Release Assets

on:
  release:
    types: [published]

# Add explicit permissions for the workflow
permissions:
  contents: write

jobs:
  build:
    name: Create consistent ZIP file
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🧹 Prepare build directory
        run: |
          echo "🚀 Creating clean build for Autocomplete Orders for WooCommerce..."
          mkdir -p build/aco
          # Copy all files to build directory
          rsync -av --exclude='.git' --exclude='.github' --exclude='.DS_Store' --exclude='build' . build/aco/
          # Clean up any unnecessary files
          find build/aco -name '.DS_Store' -type f -delete
          # Create the ZIP file
          cd build && zip -r aco.zip aco
          echo "✅ Build complete! Created aco.zip"
          ls -la

      - name: 📦 Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./build/aco.zip 